# This is the default format. 
# For more see: https://github.com/mojombo/jekyll/wiki/Permalinks

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile"]
auto: true
pygments: true
permalink: /:year/:month/:title.html
title : Yet Another Blog
description: "Programmation, entreprenariat, domotique et retrogaming."

paginate: 5



# The production_url is only used when full-domain names are needed
# such as sitemap.txt 
# Most places will/should use BASE_PATH to make the urls
#
# If you have set a CNAME (pages.github.com) set your custom domain here.
# Else if you are pushing to username.github.com, replace with your username.
# Finally if you are pushing to a GitHub project page, include the project name at the end.
#
#production_url : http://www.codeursenseine.com
#url: http://127.0.0.1:4000
url : http://www.youenchene.fr


gems:
  - jekyll-sitemap