baseURL: https://www.youenchene.fr
disablePathToLower: true
languageCode: fr
title: Yet Another Entrepreneur Blog
enableRobotsTXT: true
paginate: 10
theme: anubis

params:
  author: "Youen Chéné"
  #avatar: "/images/me.png" # used for microformats
  description: "Je suis Youen Chéné, ici, je parle Web, Sobriété Numérique, Programmation, Entreprenariat, domotique et retrogaming (Amiga)."
  # Uncomment if you need this
  # images:
  #   - images/og-featured.png # relative path to "static" directory
  customCSS:
    - css/my.css # relative path to "assets" directory (don't use main.css filename)
  # customJS:
  #   - js/main.js # relative path to "assets" directory
  dateFormat: "2006-01-02"
  paginationSinglePost: true
  style: light
  readMore: false
  disableSummary: false
  # utteranc.es support
  utterancesRepo: ""  # mandatory
  utterancesTheme: "" # optional
  utterancesIssue: "" # optional
  utterancesLabel: "" # optional
  social:
  - id: twitter
    name: youen_chene
  - id: linkedin
    name: youenchene
  - id: github
    name: youenchene
  - id: rss
    url: /feed.xml

outputFormats:
 RSS: 
  mediatype: "application/rss"
  baseName: "feed"

