baseURL: https://www.youenchene.fr
disablePathToLower: true
languageCode: fr
title: Yet Another Entrepreneur Blog
enableRobotsTXT: true
paginate: 10
theme: anubis

params:
  env: production
  author: "Youen Chéné"
  #avatar: "/images/me.png" # used for microformats
  description: "Je suis Youen Chéné, fondateur de Webvert, contributeur à Boavizta? advisor au Bear Studio. Ici, je parle Web, Sobriété Numérique, Programmation, Entreprenariat, Domotique et Rétrogaming (Amiga)."
  # images:
  intro: 'Je suis Youen Chéné, fondateur de <a href="https://www.lewebvert.fr/" target="_blank">Webvert</a>, advisor au <a href="https://www.bearstudio.fr/" target="_blank">Bear Studio</a>.'
  intro2: "Ici, je parle Web, Sobriété Numérique, Programmation, Entreprenariat, Domotique et Rétrogaming (Amiga)."

  #   - images/og-featured.png # relative path to "static" directory
  customCSS:
    - css/my.css # relative path to "assets" directory (don't use main.css filename)
  # customJS:
  #   - js/main.js # relative path to "assets" directory
  dateFormat: "2006-01-02"
  paginationSinglePost: true
  style: light
  readMore: false
  disableSummary: false
  # utteranc.es support
  utterancesRepo: ""  # mandatory
  utterancesTheme: "" # optional
  utterancesIssue: "" # optional
  utterancesLabel: "" # optional
  social:
  - id: twitter
    name: youen_chene
  - id: linkedin
    name: youenchene
  - id: github
    name: youenchene
  - id: rss
    url: /feed.xml

mediaTypes:
  text/gemini:
    suffixes:
      - "gmi"

outputFormats:
  RSS: 
    mediatype: "application/rss"
    baseName: "feed"
  GEMINI:
    name: GEMINI
    isPlainText: true
    isHTML: false
    mediaType: text/gemini
    path: "gemini/"
    protocol: "gemini://"
    permalinkable: true
  GEMINIRSS:
    baseName: "feed"
    mediaType: "application/rss+xml"
    isPlainText: false
    path: "gemini/"

outputs:
  home: ["HTML", "RSS", "GEMINI", "GEMINIRSS"]
  page: ["HTML", "GEMINI"]


deployment:
  targets:
    URL: s3://test-y?endpoint=localhost:3900&disableSSL=true&s3ForcePathStyle=true&region=garage

