name: Publish Site

on:
  push:
    branches:
      - hugo  # Set a branch to deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
        with:
          submodules: true
    - name: Publish Site
      uses: chabad360/hugo-gh-pages@master
      with:
        githubToken: ${{ secrets.PERSONAL_TOKEN }}
        cname: www.youenchene.fr
        branch: hugo
        args: --gc --minify --cleanDestinationDir